#!/bin/sh
#
# @name Innopolis VTOL
#
# @type Standard VTOL
# @class VTOL
#
# @maintainer Roman Fedorenko <r.fedorenko@innopolis.ru>
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 Aileron
# @output MAIN6 Elevator
# @output MAIN7 Rudder
# @output MAIN8 Throttle
#

. ${R}etc/init.d/rc.vtol_defaults

param set-default PWM_AUX_DIS5 950
param set-default PWM_MAIN_RATE 400
param set-default VT_TYPE 2
param set-default VT_MOT_ID 1234
param set-default VT_FW_MOT_OFFID 1234

param set-default UAVCAN_ENABLE 3
param set-default COM_ARM_CHK_ESCS 0

set MAV_TYPE 22
set MIXER inno_vtol_AAERT
set PWM_OUT 1234
set OUTPUT_MODE uavcan_esc
set OUTPUT_AUX_DEV /dev/uavcan/esc
